apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mtgengine-k8s
spec:
  hosts:
    - "*"
  gateways:
    - mtgengine-k8s
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 3000
            host: mtgengine-k8s.{{ .Values.namespace.active }}.svc.cluster.local
