apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtgengine-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mtgengine-k8s
  template:
    metadata:
      labels:
        app: mtgengine-k8s
    spec:
      containers:
        - name: mtgengine-k8s
          image:
          ports:
            - containerPort: 3000
