{{- if or .Values.secrets.topdeckApiKey .Values.secrets.anthropicApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtg.fullname" . }}
  labels: {{- include "mtg.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.topdeckApiKey }}
  TopDeck__ApiKey: {{ .Values.secrets.topdeckApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  Ai__AnthropicApiKey: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
{{- end -}}
